import { HeaderSearch } from '@/components/navbar';
import { ArtilleryType, DistanceSchema, distanceSchema } from '@/lib/schemas';
import { calculateFiringSolution } from '@/lib/solution';
import { Box, Button, Combobox, Container, Group, Input, InputBase, NumberInput, Paper, Select, Stack, Text, Title, useCombobox } from '@mantine/core';
import { useForm, zodResolver } from '@mantine/form';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [elevation, setElevation] = useState(0);

  const combobox = useCombobox({
    onDropdownClose: () => combobox.resetSelectedOption(),
  });

  const { getInputProps, values, setFieldValue, onSubmit } = useForm<DistanceSchema>({
    initialValues: {
      artilleryType: ArtilleryType.American,
      distance: 0,
    },
    validate: zodResolver(distanceSchema),
  });

  const handleChange = (values: DistanceSchema) => {
    const elevation = calculateFiringSolution(values);
    setElevation(elevation);
  }

  return (
    <>
      <Head>
        <title>HLL Toolkit | Artillery Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <HeaderSearch />

        <Container size={'xs'} p={'lg'}>
          <Stack gap={'xl'}>
            <Title>Artillery Solution Calculator</Title>
            <Box mx="auto" w={'100%'}>

              <form
                onSubmit={onSubmit(handleChange)}
              >
                <Select
                  withAsterisk
                  comboboxProps={{ withinPortal: true }}
                  label="Artillery Type"
                  placeholder="Select artillery type"
                  data={[
                    { value: ArtilleryType.American, label: 'American' },
                    { value: ArtilleryType.German, label: 'German' },
                  ]}
                  {...getInputProps('artilleryType')}
                />

                <NumberInput
                  mt={'md'}
                  withAsterisk
                  label="Distance in Meters"
                  placeholder="100"
                  {...getInputProps('distance')}
                />

                <Group justify="flex-end" mt="md">
                  <Button type="submit">Calculate</Button>
                </Group>
              </form>
            </Box>
            <Paper withBorder p="md" radius="md">
              <Group justify="apart">
                <div>
                  <Text c="dimmed" tt="uppercase" fw={700} fz="xs" >
                    Elevation
                  </Text>
                  <Text fw={700} fz="xl">
                    {elevation} MIL
                  </Text>
                </div>
              </Group>
              <Text c="dimmed" fz="sm" mt="md">
                This is the elevation you should set your artillery to.
              </Text>
            </Paper>
          </Stack>
        </Container>
      </main>
    </>
  )
}
